### ISSUE TITLE
"Cannot GET /monster/find"

### ISSUE THREAD

**Issue by vergonha** [MatheusIshiyama/ragnarok-database-api#1]
Hello, I'm trying to find a monster by name with its API but it returns an error. Am I passing the query incorrectly or something?

![image](https://user-images.githubusercontent.com/69178014/167279522-51b780dc-f690-4c8a-80d5-6c78953733c4.png)

**Comment by MatheusIshiyama** [comment]
use "monsters" instead "monster"

**Comment by vergonha** [comment]
Thanks, sir. 

I didn't try with "monsters" because in read.me it said "monster", but I saw that you already changed it.

By the way, your discord on your portfolio site doesn't work. I tried to communicate you there but the tag is not the same.
